POST https://localhost:5001/Settings HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "regions": [
    {
      "name": "Tanklar",
      "type": "Tank",
      "sections": [
        {
          "name": "Temiz Su Tankı",
          "gadgets": [
            {
              "name": "Temiz Su Tankı Şamandırası",
              "type-group": "Level",
              "type": "LevelAnalog190Ohm",
              "port": "A;10",
              "value": 99,
              "value-unit": "BasePercentage",
              "value-to-target-ratio": 2.2,
              "value-to-target-unit": "LiquidLiter",
              "complex-value": "X:10;Y:20",
              "status": "Active",
              "position-in-section": "Free",
              "id": "8de4c111-f63a-46a2-8f4c-152ef1271458"
            },
             {
              "name": "Tüketim İzleme",
              "type-group": "LiquidFlowMeter",
              "type": "LiquidFlowMeterYF06",
              "port": "D;10",
              "value": 99,
              "value-unit": "LiquidLiter",
              "status": "Active",
              "position-in-section": "Free",
              "id": "8de4c111-f63a-46a2-8f4c-152ef1271459"
            }
          ],
          "id": "6c379f58-23ab-4df7-b334-7c57dacef24c"
        },
         {
          "name": "Gri Su Tankı",
          "gadgets": [
            {
              "name": "Gri Su Tankı Şamandırası",
              "type-group": "Level",
              "type": "LevelAnalog190Ohm",
              "port": "A;11",
              "value": 99,
              "value-unit": "BasePercentage",
              "value-to-target-ratio": 1.1,
              "value-to-target-unit": "LiquidLiter",
              "complex-value": "X:10;Y:20",
              "status": "Active",
              "position-in-section": "Free",
              "id": "8de4c111-f63a-46a2-8f4c-152ef1271410",
              "actions": [
                {
                  "id": "2de4c111-f63a-46a2-8f4c-152ef1271411",
                  "order": 1,
                  "when": 96,
                  "set": 1,
                  "target-gadget": "8de4c111-f63a-46a2-8f4c-152ef1271411",
                  "on-execute-script": "@NONE"
                },
                {
                  "id": "3de4c111-f63a-46a2-8f4c-152ef1271411",
                  "order": 2,
                  "when": 5,
                  "set": 0,
                  "target-gadget": "8de4c111-f63a-46a2-8f4c-152ef1271411",
                  "on-execute-script": "@NONE"
                }
              ]
            },
             {
              "name": "Boşaltma Vanası",
              "type-group": "Valve",
              "type": "ValveNormallyClosed",
              "port": "D;11",
              "value": 0,
              "value-unit": "BaseState",
              "status": "Active",
              "position-in-section": "Free",
              "id": "8de4c111-f63a-46a2-8f4c-152ef1271411"
            }
          ],
          "id": "6c379f58-23ab-4df7-b334-7c57dacef24d"
        }
      ],
      "id": "4de047ac-2b02-4140-9be6-30751d40a4c1"
    }
  ]
}

###

GET https://localhost:5001/Settings HTTP/1.1
Content-Type: application/json
Accept: text/plain

###

GET https://localhost:5001/Gadget/GetById/8de4c111-f63a-46a2-8f4c-152ef1271410?include-actions=true HTTP/1.1
Content-Type: application/json
Accept: text/plain 

###


curl -X GET "https://localhost:5001/Gadget/GetFiltered?type-group=Level" -H "accept: text/plain"

###

POST https://localhost:5001/Gadget/SetValue/8de4c111-f63a-46a2-8f4c-152ef1271410 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "complex-value": "LOW:22",
  "value": 96
}