# This is a basic workflow to help you get started with Actions

name: Flutter
on: push
jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
      working-directory:./sp.client
    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      uses: steebchen/flutter@v1.0.0
      with:
        args: pub get

    - name: build apk
      uses: steebchen/flutter@v1.0.0
      with:
        args: build apk --release
